database:
  host: localhost
  port: 5432
  username: postgres
  password: Shohin2552
  dbname: queue-system
  sslmode: disable
  timezone: Asia/Dushanbe

server:
  host: localhost
  port: 8080
  write_timeout: 15s
  read_timeout: 15s